### ISSUE TITLE
support file names with spaces

### ISSUE THREAD

**Issue by thatsparesh** [AerisG222/NExifTool#1]
Getting file not found error when file path contains spaces

Proposed fix: Update ExifToolOptions.GetStartInfo to wrap rawFile in double quotes when building args.

**Comment by thatsparesh** [comment]
tried passing quotes when calling .GetTags, but unfortunately you are validating file path in GetTagsAsync :(

**Comment by AerisG222** [comment]
Thanks for the report!  The filename is now being wrapped in quotes, and is in version 0.2.1 on nuget.
