### ISSUE TITLE
Two, Imagewidth, and Imageheight ?

### ISSUE THREAD

**Issue by pc8181** [AerisG222/NExifTool#14]
`           
           Dim d = New ExifTool(New ExifToolOptions)
            Dim _dirInfo As New IO.DirectoryInfo(_fl)
          
          For Each filedet In _dirInfo.GetFiles("*.nef")
                Dim lit = Await d.GetTagsAsync(filedet.FullName)
                '   Trace.WriteLine($"{lit.ToString}")

                For Each vall In lit
                    '    Trace.WriteLine($"{vall.Name}")
                    Trace.WriteLine($"{vall.Name} {" - "} {vall.Value}")

                    If vall.Name = "ImageWidth" Or vall.Name = "ImageHeight" Then
                        '  Trace.WriteLine($"{vall.Name} {" - "} {vall.Value}")
                        '  If vall.Name = "ImageHeight" Then
                        '     Exit For
                        ' End If
                    End If
                Next
            Next`

i got two imagewidth and imageheight ... i guess one is thumbnail image if yes then  how can differentiate the two values  and how to get exact file dimensions plz help..

![image](https://user-images.githubusercontent.com/13380400/64058310-9f6a0780-cbc6-11e9-824b-7f2cc481e391.png)

**Comment by AerisG222** [comment]
Sorry for the late reply - I don't have a good answer for you.  I think your best bet is to probably just determine the main image resolution by grabbing the max height/width from the options.  Alternatively, if you inspect the "Group" property on the Tag, you might be able to determine which is which.  With that said, when I tested this, I did see different groups, but was not obvious to me how I would then tell which is which.

As such, I don't have any additional input here, and am not sure there is anything to do here, so am closing.

If you use exiftool directly and can send a sample command on how to identify one versus the other, open a new issue with those details and I can try to add something additional.

Thanks,
mike
