### ISSUE TITLE
Adding Argument Operation

### ISSUE THREAD

**Issue by bagsergen** [AerisG222/NExifTool#17]
Hi Mike,
There is a problem about input-output text formatting. I want to add "-E" option on the arguments. Because I have faced an encoding problem. ( https://github.com/exiftool/exiftool/issues/127 )
Can you help me ?

Thanks.

**Comment by AerisG222** [comment]
Hi @bagsergen ,

I am a bit behind in some other work, but will try to look at this over the weekend.  

Thanks,
Mike

**Comment by AerisG222** [comment]
I've just published 0.11.0 which adds `EscapeTagValues` to ExifToolOptions and when true, it will add a `-E` when calling exiftool.

I used your test value from the ticket you reference above.  Note that it looks like exiftool also does some of it's own encoding and changes some hex codes to well known entity codes, but looks like the end result is the same.

**Comment by bagsergen** [comment]
OK, I understood, thanks for your support. 🦸‍♂️ 🌟
