### ISSUE TITLE
Extracting Jpeg from Raw Image

### ISSUE THREAD

**Issue by guru248** [AerisG222/NExifTool#19]
Is there a possibility to execute the following exif command using NExifTool:
`exiftool -b -JpgFromRaw "D:\NEF.NEF" > "D:\NEFextract.jpg"`

Here, exiftool will extract the embedded `Jpeg` image from the `NEF.NEF` file and save it as `NEFextract.jpg`.
I assume we can use the FileToFileRunner class, but unsure on how to include the `updates` field.

Any help would be much appreciated.

P.S. Couldn't find a discussion page, so posting it here.

**Comment by AerisG222** [comment]
I don't believe there is a direct way to execute that command exactly, but have  you tried specifying IncludeBinaryTags = true as an option, and then look for a  'Preview Image' or 'Jpg From Raw' tag in the output?  Does that allow you to save out the data?

**Comment by AerisG222** [comment]
Hello,

Looking back at this, I believe what you are looking for might already be supported.  If you set the "IncludeBinaryTags" option to true, when you parse the tags from the exif, you should see these come back as base64 encoded values.  From there, you can clean up the data/decode from base64 to binary, write to a file, and then should be able to open the resulting image.  The original approach of going through a write process using FileToFileRunner is not the right approach, as that is geared at adding/updating exif data - not extracting it.

Sorry for the long delay, hope this is useful.

I am going to close this, but feel free to open a new issue if you run into something else.

Thanks,
mike
