### ISSUE TITLE
Feature proposal

### ISSUE THREAD

**Issue by Dzivo** [AerisG222/NExifTool#2]
Is it possible to read the from the IFormFile without saveing it first. 
Regards nice lib saved me some time :+1:

**Comment by AerisG222** [comment]
Glad you've found it useful!  I think this is possible, and will take a look at adding support for this soon.

**Comment by AerisG222** [comment]
I've just added an overload that takes a stream, and should allow you to extract the exif data without hitting the disk.  Give it a try, and let me know how you make out (v0.6.1 on nuget).

**Comment by AerisG222** [comment]
I believe this was addressed in the last update.  If this still is not working for you, please reopen or create a new issue.  Thanks for the feature request!
