### ISSUE TITLE
Need Compiled projects

### ISSUE THREAD

**Issue by pc8181** [AerisG222/NExifTool#3]
we could not open in vs2013 
please provide compiled dll files or exe file here
it does not support my version of vs2013

**Comment by AerisG222** [comment]
I do not plan on posting binaries here.  Instead, I am relying on nuget for distribution of the nuget package.  To use this library, you will also need exiftool installed and running on its own (https://www.sno.phy.queensu.ca/~phil/exiftool/install.html), as this library is just a wrapper around that.
