### ISSUE TITLE
XMP Category values

### ISSUE THREAD

**Issue by mabocek** [AerisG222/NExifTool#5]
Hey, thanks for writing this tool!

I found issue with processing XMP Category values. It returns mixed values for photo with 2 recognized faces and some values for **Region Extensions** are missing:

Results from NExifTool:
XMP Toolkit: XMP Core 5.4.0
Region Area Y: **0.4605000.471000**
Region Area W: **0.0440000.033000**
Region Area X: **0.4450000.325500**
Region Area H: **0.0590000.044000**
Region Area Unit: **normalizednormalized**
Region Type: **FaceFace**
Region Applied To Dimensions H: 3024
Region Applied To Dimensions W: 4032
Region Applied To Dimensions Unit: pixel

Results from Exif Tool CLI:
XMP Toolkit                     : XMP Core 5.4.0
Region Area Y                   : 0.460500, 0.471000
Region Area W                   : 0.044000, 0.033000
Region Area X                   : 0.445000, 0.325500
Region Area H                   : 0.059000, 0.044000
Region Area Unit                : normalized, normalized
Region Type                     : Face, Face
Region Extensions Angle Info Yaw: 270
Region Extensions Angle Info Roll: 0
Region Extensions Confidence Level: 99
Region Extensions Time Stamp    : 1312152977276
Region Extensions Face ID       : 3
Region Applied To Dimensions H  : 3024
Region Applied To Dimensions W  : 4032
Region Applied To Dimensions Unit: pixel

There is attached image, which caused issues:
![img_0037](https://user-images.githubusercontent.com/1961642/35781602-96011d02-09ec-11e8-9335-aaa98042aa5a.JPG)

**Comment by AerisG222** [comment]
Thanks for the detailed report!  I will look at this when I find some free time.

**Comment by AerisG222** [comment]
After some testing, I believe the tags were being parsed and made available, but you would have had to find these by looking by the Tag ID, such as "apple-fi:RegionsRegionListExtensionsAngleInfoYaw", as the name field is not currently set in this condition.

I have made a small update to also populate the name when we encounter a tag that is not known ahead of time.  The name will either match the ID, or the value after the last ':' in the tag id.  In the above example, you should now see the tag when searching for a name with RegionsRegionListExtensionsAngleInfoYaw.

This update is available in v0.8.2.  

Also, I hope you don't mind, but I have included the example picture above in the test project.  If you do mind, please let me know and I will remove the image and test case.

Thanks,
-Mike

**Comment by AerisG222** [comment]
Sorry for the long delay, I have just released a pre-release version (0.9.0-beta) which should address most scenarios for getting list data out.  You can see an example in the `overhaul` branch; have a look at ParseTests.cs:GetRegionExtensionsTags().

Note that there were a number of breaking changes introduced, but hopefully they are pretty straightforward to work through.

Thanks!

**Comment by AerisG222** [comment]
This should be addressed in v0.9.0.
