### ISSUE TITLE
List-type tags such as Keywords return concatenated string of all values.

### ISSUE THREAD

**Issue by dm413** [AerisG222/NExifTool#9]
I am trying to change the IPTC keywords tag. The `GetTagsAsync ` method returns a tag with name "Keywords", but the value is a single string with all the keywords concatenated without separators. I would prefer a `List<string>`, but at the very least we need quote marks and separators.

Then when writing the keywords using `OverwriteTagsAsync`, how would I create the `SetOperation`?

Thanks

**Comment by AerisG222** [comment]
Thanks for the report.  I have a lot going on at the moment, but will try to find some time to have a look at this.  If possible, could you attach a sample image with those fields populated?  feel free to black out the actual image

Thanks

**Comment by AerisG222** [comment]
This is great - thank you for the sample!

**Comment by AerisG222** [comment]
@dm413 I've just published a v0.9.0-beta which hopefully will appear as an update if you enable pre-release packages.  I made a lot of changes that I think will be more maintainable, but does introduce a lot of breaking changes, but should be pretty straightforward to address.

As an example for your read and write scenarios, please look at ParseTests.cs:GetTagsFromImageWithKeywords() and any of the tests in WriteTests.cs.    When you have some time, give it a try and let me know if it works for you, and if you have any suggestions on how to improve.

Thanks!

**Comment by AerisG222** [comment]
Sorry, to view the examples in the test code, you will need to look in the `overhaul` branch

**Comment by AerisG222** [comment]
Thanks for testing this out!  v0.9.0 should be available on nuget now, with no changes other than version number.
